// export default [
//   {
//     id: 1,
//     title: "Firebase",
//     img: "./../../images/Firebase-logo.png",
//     isGuessed: false,
//     isShowing: false,
//   },
//   {
//     id: 2,
//     title: "Firebase",
//     img: "/images/Firebase-logo.png",
//     isGuessed: false,
//     isShowing: false,
//   },

//   {
//     id: 14,
//     title: "Nginx",
//     img: "/images/Webpack-logo.png",
//     isGuessed: false,
//     isShowing: false,
//   },
//   {
//     id: 15,
//     title: "Nginx",
//     img: "./../../images/Webstorm-logo.png",
//     isGuessed: false,
//     isShowing: false,
//   },
// ];

// import firebase from './../src/images/Firebase-logo.png'

export default [
  {
    id: 1,
    title: "Firebase",
    img: "./../../images/Firebase-logo.png",
    isGuessed: false,
    isShowing: true,
  },
  {
    id: 2,
    title: "Firebase",
    img: "/images/Firebase-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 3,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 4,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 5,
    title: "Nodejs",
    img: "./../../images/Nodejs-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 6,
    title: "Nodejs",
    img: "/images/Nodejs-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 7,
    title: "React",
    img: "./../../images/React-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 8,
    title: "React",
    img: "./../../images/React-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 9,
    title: "Redux",
    img: "./../../images/Redux-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 10,
    title: "Redux",
    img: "/images/Redux-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 11,
    title: "Typescript",
    img: "./../../images/Typescript-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 12,
    title: "Typescript",
    img: "./../../images/Typescript-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 13,
    title: "Webpack",
    img: "./../../images/Webpack-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 14,
    title: "Webpack",
    img: "/images/Webpack-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 15,
    title: "Webstorm",
    img: "./../../images/Webstorm-logo.png",
    isGuessed: false,
    isShowing: false,
  },
  {
    id: 16,
    title: "Webstorm",
    img: "./../../images/Webstorm-logo.png",
    isGuessed: false,
    isShowing: false,
  },
];
