export default [
  {
    id: 1,
    title: "Firebase",
    img: "./../../images/Firebase-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 2,
    title: "Firebase",
    img: "/images/Firebase-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 3,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 4,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 1,
    title: "Firebase",
    img: "./../../images/Firebase-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 2,
    title: "Firebase",
    img: "/images/Firebase-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 3,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 4,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 1,
    title: "Firebase",
    img: "./../../images/Firebase-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 2,
    title: "Firebase",
    img: "/images/Firebase-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 3,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 4,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 1,
    title: "Firebase",
    img: "./../../images/Firebase-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 2,
    title: "Firebase",
    img: "/images/Firebase-logo.png",
    isGuessed: true,
    isShowing: true,
  },
  {
    id: 3,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: false,
  },
  {
    id: 4,
    title: "Nginx",
    img: "./../../images/Nginx-featured-logo.png",
    isGuessed: true,
    isShowing: true,
  },
];
